server:
  port: 0

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page-size: 2000
# Global Page Config

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.intance_id:${random.value}}

token:
  expiration_time: 8640000
  secret: user_token